Change handle_packet_in method behavior
kytos/of_l2ls pull request #19
Opened 2020-08-27 17:33 UTC by gleybersonandrade

This commit changes handle_packet_in method to check if the ports inside actions list aren't disable from 'config' field (i.e.: OFPPC_NO_FWD flag)  when sending a packet_out message..

2020-08-31 17:02 UTC, gleybersonandrade commented
> Couldn't the check be in `_create_packet_out`?

It can be, it's really better. I'll change this.

Thanks @ajoaoff

2020-09-22 13:30 UTC, josemauro approved these changes

2020-10-12 15:23 UTC, italovalcy commented
Hi guys,

The patch seems to be very good for me, except for the lack of logs, exceptions, or any other information that could help the kytos user to know that the packet_out is not being sent due to the port disable. Don't you guys think it should register a log event saying the packet_out was not sent and why? Especially here: https://github.com/kytos/of_l2ls/pull/19/files#diff-5bc02cefb3ea9e27f1a6776eabd1935dR133-R135

2020-10-13 16:42 UTC, beraldoleal requested changes

2020-10-13 16:42 UTC, beraldoleal commented on main.py
> +                iface = switch.get_interface_by_port_no(port)
My only concern is here, you are querying twice, in the worst-case scenario. IIUC, AttributeError is not raised by `get_interface_by_port_no`, so my suggestion is something like this:
```python
try:
   port_number = port.value
except AttributeError:
   port_number = port
iface = switch.get_interface_by_port_no(port_number)
```

Or we should handle this properly inside `get_interface_by_port_no`.

2020-10-13 16:42 UTC, beraldoleal commented on main.py
> +                iface = switch.get_interface_by_port_no(port)
Same here.

2020-12-23 16:19 UTC, hdiogenes commented
Superseded by #21.

2020-12-23 16:19 UTC, closed without merging